# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.26

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake.exe

# The command to remove a file.
RM = /usr/bin/cmake.exe -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /g/ProgrammingProjects/Electron

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /g/ProgrammingProjects/Electron

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/bin/ccmake.exe -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake.exe --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /g/ProgrammingProjects/Electron/CMakeFiles /g/ProgrammingProjects/Electron//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /g/ProgrammingProjects/Electron/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named Electron

# Build rule for target.
Electron: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 Electron
.PHONY : Electron

# fast build rule for target.
Electron/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Electron.dir/build.make CMakeFiles/Electron.dir/build
.PHONY : Electron/fast

src/GLEW/glew.o: src/GLEW/glew.c.o
.PHONY : src/GLEW/glew.o

# target to build an object file
src/GLEW/glew.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Electron.dir/build.make CMakeFiles/Electron.dir/src/GLEW/glew.c.o
.PHONY : src/GLEW/glew.c.o

src/GLEW/glew.i: src/GLEW/glew.c.i
.PHONY : src/GLEW/glew.i

# target to preprocess a source file
src/GLEW/glew.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Electron.dir/build.make CMakeFiles/Electron.dir/src/GLEW/glew.c.i
.PHONY : src/GLEW/glew.c.i

src/GLEW/glew.s: src/GLEW/glew.c.s
.PHONY : src/GLEW/glew.s

# target to generate assembly for a file
src/GLEW/glew.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Electron.dir/build.make CMakeFiles/Electron.dir/src/GLEW/glew.c.s
.PHONY : src/GLEW/glew.c.s

src/ImGui/imgui.o: src/ImGui/imgui.cpp.o
.PHONY : src/ImGui/imgui.o

# target to build an object file
src/ImGui/imgui.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Electron.dir/build.make CMakeFiles/Electron.dir/src/ImGui/imgui.cpp.o
.PHONY : src/ImGui/imgui.cpp.o

src/ImGui/imgui.i: src/ImGui/imgui.cpp.i
.PHONY : src/ImGui/imgui.i

# target to preprocess a source file
src/ImGui/imgui.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Electron.dir/build.make CMakeFiles/Electron.dir/src/ImGui/imgui.cpp.i
.PHONY : src/ImGui/imgui.cpp.i

src/ImGui/imgui.s: src/ImGui/imgui.cpp.s
.PHONY : src/ImGui/imgui.s

# target to generate assembly for a file
src/ImGui/imgui.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Electron.dir/build.make CMakeFiles/Electron.dir/src/ImGui/imgui.cpp.s
.PHONY : src/ImGui/imgui.cpp.s

src/ImGui/imgui_demo.o: src/ImGui/imgui_demo.cpp.o
.PHONY : src/ImGui/imgui_demo.o

# target to build an object file
src/ImGui/imgui_demo.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Electron.dir/build.make CMakeFiles/Electron.dir/src/ImGui/imgui_demo.cpp.o
.PHONY : src/ImGui/imgui_demo.cpp.o

src/ImGui/imgui_demo.i: src/ImGui/imgui_demo.cpp.i
.PHONY : src/ImGui/imgui_demo.i

# target to preprocess a source file
src/ImGui/imgui_demo.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Electron.dir/build.make CMakeFiles/Electron.dir/src/ImGui/imgui_demo.cpp.i
.PHONY : src/ImGui/imgui_demo.cpp.i

src/ImGui/imgui_demo.s: src/ImGui/imgui_demo.cpp.s
.PHONY : src/ImGui/imgui_demo.s

# target to generate assembly for a file
src/ImGui/imgui_demo.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Electron.dir/build.make CMakeFiles/Electron.dir/src/ImGui/imgui_demo.cpp.s
.PHONY : src/ImGui/imgui_demo.cpp.s

src/ImGui/imgui_draw.o: src/ImGui/imgui_draw.cpp.o
.PHONY : src/ImGui/imgui_draw.o

# target to build an object file
src/ImGui/imgui_draw.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Electron.dir/build.make CMakeFiles/Electron.dir/src/ImGui/imgui_draw.cpp.o
.PHONY : src/ImGui/imgui_draw.cpp.o

src/ImGui/imgui_draw.i: src/ImGui/imgui_draw.cpp.i
.PHONY : src/ImGui/imgui_draw.i

# target to preprocess a source file
src/ImGui/imgui_draw.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Electron.dir/build.make CMakeFiles/Electron.dir/src/ImGui/imgui_draw.cpp.i
.PHONY : src/ImGui/imgui_draw.cpp.i

src/ImGui/imgui_draw.s: src/ImGui/imgui_draw.cpp.s
.PHONY : src/ImGui/imgui_draw.s

# target to generate assembly for a file
src/ImGui/imgui_draw.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Electron.dir/build.make CMakeFiles/Electron.dir/src/ImGui/imgui_draw.cpp.s
.PHONY : src/ImGui/imgui_draw.cpp.s

src/ImGui/imgui_impl_glfw.o: src/ImGui/imgui_impl_glfw.cpp.o
.PHONY : src/ImGui/imgui_impl_glfw.o

# target to build an object file
src/ImGui/imgui_impl_glfw.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Electron.dir/build.make CMakeFiles/Electron.dir/src/ImGui/imgui_impl_glfw.cpp.o
.PHONY : src/ImGui/imgui_impl_glfw.cpp.o

src/ImGui/imgui_impl_glfw.i: src/ImGui/imgui_impl_glfw.cpp.i
.PHONY : src/ImGui/imgui_impl_glfw.i

# target to preprocess a source file
src/ImGui/imgui_impl_glfw.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Electron.dir/build.make CMakeFiles/Electron.dir/src/ImGui/imgui_impl_glfw.cpp.i
.PHONY : src/ImGui/imgui_impl_glfw.cpp.i

src/ImGui/imgui_impl_glfw.s: src/ImGui/imgui_impl_glfw.cpp.s
.PHONY : src/ImGui/imgui_impl_glfw.s

# target to generate assembly for a file
src/ImGui/imgui_impl_glfw.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Electron.dir/build.make CMakeFiles/Electron.dir/src/ImGui/imgui_impl_glfw.cpp.s
.PHONY : src/ImGui/imgui_impl_glfw.cpp.s

src/ImGui/imgui_impl_opengl3.o: src/ImGui/imgui_impl_opengl3.cpp.o
.PHONY : src/ImGui/imgui_impl_opengl3.o

# target to build an object file
src/ImGui/imgui_impl_opengl3.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Electron.dir/build.make CMakeFiles/Electron.dir/src/ImGui/imgui_impl_opengl3.cpp.o
.PHONY : src/ImGui/imgui_impl_opengl3.cpp.o

src/ImGui/imgui_impl_opengl3.i: src/ImGui/imgui_impl_opengl3.cpp.i
.PHONY : src/ImGui/imgui_impl_opengl3.i

# target to preprocess a source file
src/ImGui/imgui_impl_opengl3.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Electron.dir/build.make CMakeFiles/Electron.dir/src/ImGui/imgui_impl_opengl3.cpp.i
.PHONY : src/ImGui/imgui_impl_opengl3.cpp.i

src/ImGui/imgui_impl_opengl3.s: src/ImGui/imgui_impl_opengl3.cpp.s
.PHONY : src/ImGui/imgui_impl_opengl3.s

# target to generate assembly for a file
src/ImGui/imgui_impl_opengl3.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Electron.dir/build.make CMakeFiles/Electron.dir/src/ImGui/imgui_impl_opengl3.cpp.s
.PHONY : src/ImGui/imgui_impl_opengl3.cpp.s

src/ImGui/imgui_stdlib.o: src/ImGui/imgui_stdlib.cpp.o
.PHONY : src/ImGui/imgui_stdlib.o

# target to build an object file
src/ImGui/imgui_stdlib.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Electron.dir/build.make CMakeFiles/Electron.dir/src/ImGui/imgui_stdlib.cpp.o
.PHONY : src/ImGui/imgui_stdlib.cpp.o

src/ImGui/imgui_stdlib.i: src/ImGui/imgui_stdlib.cpp.i
.PHONY : src/ImGui/imgui_stdlib.i

# target to preprocess a source file
src/ImGui/imgui_stdlib.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Electron.dir/build.make CMakeFiles/Electron.dir/src/ImGui/imgui_stdlib.cpp.i
.PHONY : src/ImGui/imgui_stdlib.cpp.i

src/ImGui/imgui_stdlib.s: src/ImGui/imgui_stdlib.cpp.s
.PHONY : src/ImGui/imgui_stdlib.s

# target to generate assembly for a file
src/ImGui/imgui_stdlib.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Electron.dir/build.make CMakeFiles/Electron.dir/src/ImGui/imgui_stdlib.cpp.s
.PHONY : src/ImGui/imgui_stdlib.cpp.s

src/ImGui/imgui_tables.o: src/ImGui/imgui_tables.cpp.o
.PHONY : src/ImGui/imgui_tables.o

# target to build an object file
src/ImGui/imgui_tables.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Electron.dir/build.make CMakeFiles/Electron.dir/src/ImGui/imgui_tables.cpp.o
.PHONY : src/ImGui/imgui_tables.cpp.o

src/ImGui/imgui_tables.i: src/ImGui/imgui_tables.cpp.i
.PHONY : src/ImGui/imgui_tables.i

# target to preprocess a source file
src/ImGui/imgui_tables.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Electron.dir/build.make CMakeFiles/Electron.dir/src/ImGui/imgui_tables.cpp.i
.PHONY : src/ImGui/imgui_tables.cpp.i

src/ImGui/imgui_tables.s: src/ImGui/imgui_tables.cpp.s
.PHONY : src/ImGui/imgui_tables.s

# target to generate assembly for a file
src/ImGui/imgui_tables.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Electron.dir/build.make CMakeFiles/Electron.dir/src/ImGui/imgui_tables.cpp.s
.PHONY : src/ImGui/imgui_tables.cpp.s

src/ImGui/imgui_widgets.o: src/ImGui/imgui_widgets.cpp.o
.PHONY : src/ImGui/imgui_widgets.o

# target to build an object file
src/ImGui/imgui_widgets.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Electron.dir/build.make CMakeFiles/Electron.dir/src/ImGui/imgui_widgets.cpp.o
.PHONY : src/ImGui/imgui_widgets.cpp.o

src/ImGui/imgui_widgets.i: src/ImGui/imgui_widgets.cpp.i
.PHONY : src/ImGui/imgui_widgets.i

# target to preprocess a source file
src/ImGui/imgui_widgets.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Electron.dir/build.make CMakeFiles/Electron.dir/src/ImGui/imgui_widgets.cpp.i
.PHONY : src/ImGui/imgui_widgets.cpp.i

src/ImGui/imgui_widgets.s: src/ImGui/imgui_widgets.cpp.s
.PHONY : src/ImGui/imgui_widgets.s

# target to generate assembly for a file
src/ImGui/imgui_widgets.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Electron.dir/build.make CMakeFiles/Electron.dir/src/ImGui/imgui_widgets.cpp.s
.PHONY : src/ImGui/imgui_widgets.cpp.s

src/ImGuiFileDialog.o: src/ImGuiFileDialog.cpp.o
.PHONY : src/ImGuiFileDialog.o

# target to build an object file
src/ImGuiFileDialog.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Electron.dir/build.make CMakeFiles/Electron.dir/src/ImGuiFileDialog.cpp.o
.PHONY : src/ImGuiFileDialog.cpp.o

src/ImGuiFileDialog.i: src/ImGuiFileDialog.cpp.i
.PHONY : src/ImGuiFileDialog.i

# target to preprocess a source file
src/ImGuiFileDialog.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Electron.dir/build.make CMakeFiles/Electron.dir/src/ImGuiFileDialog.cpp.i
.PHONY : src/ImGuiFileDialog.cpp.i

src/ImGuiFileDialog.s: src/ImGuiFileDialog.cpp.s
.PHONY : src/ImGuiFileDialog.s

# target to generate assembly for a file
src/ImGuiFileDialog.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Electron.dir/build.make CMakeFiles/Electron.dir/src/ImGuiFileDialog.cpp.s
.PHONY : src/ImGuiFileDialog.cpp.s

src/app.o: src/app.cpp.o
.PHONY : src/app.o

# target to build an object file
src/app.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Electron.dir/build.make CMakeFiles/Electron.dir/src/app.cpp.o
.PHONY : src/app.cpp.o

src/app.i: src/app.cpp.i
.PHONY : src/app.i

# target to preprocess a source file
src/app.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Electron.dir/build.make CMakeFiles/Electron.dir/src/app.cpp.i
.PHONY : src/app.cpp.i

src/app.s: src/app.cpp.s
.PHONY : src/app.s

# target to generate assembly for a file
src/app.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Electron.dir/build.make CMakeFiles/Electron.dir/src/app.cpp.s
.PHONY : src/app.cpp.s

src/electron.o: src/electron.cpp.o
.PHONY : src/electron.o

# target to build an object file
src/electron.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Electron.dir/build.make CMakeFiles/Electron.dir/src/electron.cpp.o
.PHONY : src/electron.cpp.o

src/electron.i: src/electron.cpp.i
.PHONY : src/electron.i

# target to preprocess a source file
src/electron.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Electron.dir/build.make CMakeFiles/Electron.dir/src/electron.cpp.i
.PHONY : src/electron.cpp.i

src/electron.s: src/electron.cpp.s
.PHONY : src/electron.s

# target to generate assembly for a file
src/electron.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Electron.dir/build.make CMakeFiles/Electron.dir/src/electron.cpp.s
.PHONY : src/electron.cpp.s

src/graphics_core.o: src/graphics_core.cpp.o
.PHONY : src/graphics_core.o

# target to build an object file
src/graphics_core.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Electron.dir/build.make CMakeFiles/Electron.dir/src/graphics_core.cpp.o
.PHONY : src/graphics_core.cpp.o

src/graphics_core.i: src/graphics_core.cpp.i
.PHONY : src/graphics_core.i

# target to preprocess a source file
src/graphics_core.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Electron.dir/build.make CMakeFiles/Electron.dir/src/graphics_core.cpp.i
.PHONY : src/graphics_core.cpp.i

src/graphics_core.s: src/graphics_core.cpp.s
.PHONY : src/graphics_core.s

# target to generate assembly for a file
src/graphics_core.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Electron.dir/build.make CMakeFiles/Electron.dir/src/graphics_core.cpp.s
.PHONY : src/graphics_core.cpp.s

src/project_configuration.o: src/project_configuration.cpp.o
.PHONY : src/project_configuration.o

# target to build an object file
src/project_configuration.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Electron.dir/build.make CMakeFiles/Electron.dir/src/project_configuration.cpp.o
.PHONY : src/project_configuration.cpp.o

src/project_configuration.i: src/project_configuration.cpp.i
.PHONY : src/project_configuration.i

# target to preprocess a source file
src/project_configuration.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Electron.dir/build.make CMakeFiles/Electron.dir/src/project_configuration.cpp.i
.PHONY : src/project_configuration.cpp.i

src/project_configuration.s: src/project_configuration.cpp.s
.PHONY : src/project_configuration.s

# target to generate assembly for a file
src/project_configuration.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Electron.dir/build.make CMakeFiles/Electron.dir/src/project_configuration.cpp.s
.PHONY : src/project_configuration.cpp.s

src/render_preview.o: src/render_preview.cpp.o
.PHONY : src/render_preview.o

# target to build an object file
src/render_preview.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Electron.dir/build.make CMakeFiles/Electron.dir/src/render_preview.cpp.o
.PHONY : src/render_preview.cpp.o

src/render_preview.i: src/render_preview.cpp.i
.PHONY : src/render_preview.i

# target to preprocess a source file
src/render_preview.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Electron.dir/build.make CMakeFiles/Electron.dir/src/render_preview.cpp.i
.PHONY : src/render_preview.cpp.i

src/render_preview.s: src/render_preview.cpp.s
.PHONY : src/render_preview.s

# target to generate assembly for a file
src/render_preview.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Electron.dir/build.make CMakeFiles/Electron.dir/src/render_preview.cpp.s
.PHONY : src/render_preview.cpp.s

src/shortcuts.o: src/shortcuts.cpp.o
.PHONY : src/shortcuts.o

# target to build an object file
src/shortcuts.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Electron.dir/build.make CMakeFiles/Electron.dir/src/shortcuts.cpp.o
.PHONY : src/shortcuts.cpp.o

src/shortcuts.i: src/shortcuts.cpp.i
.PHONY : src/shortcuts.i

# target to preprocess a source file
src/shortcuts.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Electron.dir/build.make CMakeFiles/Electron.dir/src/shortcuts.cpp.i
.PHONY : src/shortcuts.cpp.i

src/shortcuts.s: src/shortcuts.cpp.s
.PHONY : src/shortcuts.s

# target to generate assembly for a file
src/shortcuts.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Electron.dir/build.make CMakeFiles/Electron.dir/src/shortcuts.cpp.s
.PHONY : src/shortcuts.cpp.s

src/ui_core.o: src/ui_core.cpp.o
.PHONY : src/ui_core.o

# target to build an object file
src/ui_core.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Electron.dir/build.make CMakeFiles/Electron.dir/src/ui_core.cpp.o
.PHONY : src/ui_core.cpp.o

src/ui_core.i: src/ui_core.cpp.i
.PHONY : src/ui_core.i

# target to preprocess a source file
src/ui_core.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Electron.dir/build.make CMakeFiles/Electron.dir/src/ui_core.cpp.i
.PHONY : src/ui_core.cpp.i

src/ui_core.s: src/ui_core.cpp.s
.PHONY : src/ui_core.s

# target to generate assembly for a file
src/ui_core.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Electron.dir/build.make CMakeFiles/Electron.dir/src/ui_core.cpp.s
.PHONY : src/ui_core.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... Electron"
	@echo "... src/GLEW/glew.o"
	@echo "... src/GLEW/glew.i"
	@echo "... src/GLEW/glew.s"
	@echo "... src/ImGui/imgui.o"
	@echo "... src/ImGui/imgui.i"
	@echo "... src/ImGui/imgui.s"
	@echo "... src/ImGui/imgui_demo.o"
	@echo "... src/ImGui/imgui_demo.i"
	@echo "... src/ImGui/imgui_demo.s"
	@echo "... src/ImGui/imgui_draw.o"
	@echo "... src/ImGui/imgui_draw.i"
	@echo "... src/ImGui/imgui_draw.s"
	@echo "... src/ImGui/imgui_impl_glfw.o"
	@echo "... src/ImGui/imgui_impl_glfw.i"
	@echo "... src/ImGui/imgui_impl_glfw.s"
	@echo "... src/ImGui/imgui_impl_opengl3.o"
	@echo "... src/ImGui/imgui_impl_opengl3.i"
	@echo "... src/ImGui/imgui_impl_opengl3.s"
	@echo "... src/ImGui/imgui_stdlib.o"
	@echo "... src/ImGui/imgui_stdlib.i"
	@echo "... src/ImGui/imgui_stdlib.s"
	@echo "... src/ImGui/imgui_tables.o"
	@echo "... src/ImGui/imgui_tables.i"
	@echo "... src/ImGui/imgui_tables.s"
	@echo "... src/ImGui/imgui_widgets.o"
	@echo "... src/ImGui/imgui_widgets.i"
	@echo "... src/ImGui/imgui_widgets.s"
	@echo "... src/ImGuiFileDialog.o"
	@echo "... src/ImGuiFileDialog.i"
	@echo "... src/ImGuiFileDialog.s"
	@echo "... src/app.o"
	@echo "... src/app.i"
	@echo "... src/app.s"
	@echo "... src/electron.o"
	@echo "... src/electron.i"
	@echo "... src/electron.s"
	@echo "... src/graphics_core.o"
	@echo "... src/graphics_core.i"
	@echo "... src/graphics_core.s"
	@echo "... src/project_configuration.o"
	@echo "... src/project_configuration.i"
	@echo "... src/project_configuration.s"
	@echo "... src/render_preview.o"
	@echo "... src/render_preview.i"
	@echo "... src/render_preview.s"
	@echo "... src/shortcuts.o"
	@echo "... src/shortcuts.i"
	@echo "... src/shortcuts.s"
	@echo "... src/ui_core.o"
	@echo "... src/ui_core.i"
	@echo "... src/ui_core.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

